### ISSUE TITLE
Handling of external data files (inputs and outputs) for testing

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/EchoPro#106]
Currently the 2019 inputs and 2019 Matlab EchoPro outputs are stored in Google Drive folders with access limited to team members (UW and FEAT). The inputs are required for all tests (and the notebooks), while the outputs are used in some of the tests. At this time we're unable to set up the tests as GH Actions if the outputs and specially the inputs are not directly accessible.

**Comment by leewujung** [comment]
Using mock data files will also make it possible to resolve #13 -- I think it should be part of the goals.

**Comment by leewujung** [comment]
I am going to close this issue now since there's no details on which files are used for which purpose, and as such #151 supersedes this issue.
