### ISSUE TITLE
Document core classes

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/EchoPro#113]
### Each (major?) class

- Core class
  - survey.Survey
  - All actions and computations are orchestrated from this class
- computation
  - computation.transect_results.ComputeTransectVariables
  - computation.semivariogram.SemiVariogram
  - computation.kriging.Kriging
  - computation.kriging_variables.ComputeKrigingVariables
  - computation.bootstrapping.Bootstrapping
- data loaders
  - data_loader.kriging_mesh.KrigingMesh
  - data_loader.biological_data.LoadBioData
  - data_loader.stratification_data.LoadStrataData
- report generation
  - reports.Reports

### Other notes

- `bio_calc`: From `computation.transect_results.ComputeTransectVariables`; and also from Kriging?
  - Categorize the long list of df's and gdf's available on `bio_calc`; eg, `kriging`, `kriging_bin`, `transect`, `weight_fraction`, etc. These can be categorized either by prefix or suffix
  - Only the 6 "results" tables are gdf's: transect vs kriging, and sex (all[empty]/male/female). eg, `transect_results_male_gdf`
  - `bin_ds` is an xarray dataset
  - Most of the other objects are dataframes (`_df`), but there are a few others that don't have a clarifying suffix: `strata_sig_b`, `all_strata`, `missing_strata`, `percentage_transects_selected`, `sel_tran_strata_choice` (a dict), `stratum_choices` (a dict)
- For the classes, separate out public from private methods
- To get all the methods and attributes/properties of an object (a class), use this: `[(name, type(myobject.__getattribute__(name))) for name in dir(myobject) if not name.startswith("__")]`

**Comment by emiliom** [comment]
I've been working on this. I'll finalize PR #131 on Friday.

**Comment by leewujung** [comment]
I'll close this now as I just closed #131 and the data structure is being changed.
