### ISSUE TITLE
Initial documentation in the Jupyter Book

### ISSUE THREAD

**Issue by emiliom** [uw-echospace/EchoPro#114]
Draft outline.

- [ ] Introduction
- [ ] Installation and setup
- Workflow
  - [x] Describe it conceptually first, briefly, referring to the main objects
  - [x] Brief, core workflow code. Can be a shortened version of the main workflow notebook, and can be composed as a notebook itself. `workflow_minimal.ipynb`
  - [x] Point to the extended workflow in `echopro_workflow.ipynb`
    - Map plots and other plots
    - Steps not included in the core workflow page
  - [ ] Other areas
    - SemiVariogram widget, interactive generation
    - Kriging mesh generation
    - Transect subsetting and bootstrapping
- Classes and main data structures. #113
  - [ ] Listing with docstrings as descriptions
  - [ ] Highlights, what they do
  - [ ] (Geo)DataFrames and their contents
  - [ ] Inputs, processed intermediates, and "results"
  - [ ] `bio_calc` object
- Files, inputs/outputs
  - [ ] Config files
  - [ ] Input files. #111
  - [ ] Output files (reports). #112
- A separate page can describe each major "results" gdf in detail

**Comment by emiliom** [comment]
Refer also to [Chu's EchoPro program description Google Doc (2/24/2022)](https://docs.google.com/document/d/1i1g4pYsdZ6-T0oXqh23UaJhAyRCCnwFS/edit)

**Comment by leewujung** [comment]
Closing this now since many items are outdated and the content will be covered in the next month or so along with the refactoring work in v0.4.X.
