### ISSUE TITLE
Refactor functions called in `Survey.load_survey_data`

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/EchoPro#128]
Below are functions and function calls that I think can be simplified.

I'll continue to add to this as I go, and will also create issues for additional functions to be added that are currently marked as TODOs.

- [x] #138
- [x] #136
- [x] #137
- [x] #132
- [x] #130
- [x] #149
- [x] #134
- [x] #135

**Comment by brandynlucca** [comment]
> * [ ]  [Absorb `_process_nasc_data` into `load_nasc_df` #137](https://github.com/uw-echospace/EchoPro/issues/137)

I went ahead and checked some of these off since they've been addressed. For this one, it seems like this has been addressed (when perusing the linked Issues), but I wasn't sure if this is also inclusive of importing the separate NASC data files as a missing feature/functionality.

**Comment by leewujung** [comment]
It wasn't intended to include importing the separate NASC data files, because I did not know about that at that time...

I just checked that box off also. I guess we're ready to close this! 🎉

I'll close those resolved issues that are still open also.
