### ISSUE TITLE
Create routines to check the format of the input files

### ISSUE THREAD

**Issue by b-reyes** [uw-echospace/EchoPro#13]
Currently, we require a strict form for the input files. We need to ensure that the user satisfies this form. To do this, we need to provide a couple of checks before we begin:

1. The input Excel files have the correct column headers (necessary because we use Pandas).
2. The input Excel files have correctly defined values e.g. appropriate NaN values, no strings in integer/float columns.
3. The configuration files have all necessary variables defined and these values are of the correct type. Here we could also check that the paths provided exist.

**Comment by leewujung** [comment]
Closing this now as the content is captured in #125 and #149.
