### ISSUE TITLE
Remove input argument `file_type` from `load_survey_data`

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/EchoPro#138]
I don't see `file_type` set to anything other than `all` used anywhere in the code, but saw something getting commented out. I wonder if this was a remnant used for debugging at some point.

@emiliom : Do you know if there is anything that I may have missed?

**Comment by emiliom** [comment]
I don't remember if there was ever any reason to have that parameter. But I don't see any use for ever loading only a subset of the input data files.

**Comment by leewujung** [comment]
Sounds good. Let's remove this then.

**Comment by leewujung** [comment]
This is addressed via #161.
