### ISSUE TITLE
What is the difference between `specimen_df` and `length_df`?

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/EchoPro#142]
`specimen_df` comes from the Specimen file and `length_df` comes from the Length file, but these files contain overlapping info. How are they different?

This is important in resolving questions about how averaged TS is estimated in `_get_strata_sig_b` -- see #143 .

In the code there are multiple places referencing "station 1" (uses `length_df`) and "station 2" (uses `specimen_df`). Is this just from different physical stations on the boat, and each station does different sampling and measure different things?

**Comment by emiliom** [comment]
My understanding is that one station (I think station 1) is where the extensive length measurements are made, resulting in the length distributions (`length` and `length_count`, plus `sex`) found in the Length file. The other station (station 2) is where more intensive measurements are made on a subset of fish, resulting in `weight` and `age` in addition to `length` and `sex`; that's the Specimen file. 

I went through the documents from the FEAT team on Google Drive and couldn't find a dedicated, clear description of these "stations" and how they lead to the two different files. But I found a reference to the "length" vs "specimen" files (with those names) in page 20 of the document ["Pacific Hake "Integrated Acoustic and Trawl Survey Methods – DRAFT Jan 31 2017"](https://docs.google.com/document/d/1ve6tJh17VVd5wc7Smzdkxv180YoBtzmF/edit?usp=drive_link&ouid=116310403485720481430&rtpof=true&sd=true).

**Comment by leewujung** [comment]
@emiliom : Thanks for the info! When I was on the boat there were indeed 2 stations on the ship. The station I was helping with did sexing with length measurements (so that's probably station 1), and the other was more sophisticated and did a lot more sample collection (so that's probably stations 2). I will connect with Alicia and RT to get a definitive answer.

**Comment by emiliom** [comment]
https://github.com/uw-echospace/hake-IGP/issues/1#issuecomment-1242623893 : A link to an earlier explanation of this distinction. It doesn't add much to what I stated above, but it may be helpful background.

**Comment by rebeccathomas-NOAA** [comment]
Alicia would be the one with the definitive answer, but yes, one set of data comes from one physical station ("lengths"), where just lengths and sex are taken. The other set of data comes from another physical station ("specimen", where lengths, weights, otoliths, and more detailed samples are taken.  From what I read above, (and my acknowledging that I'm not Alicia), you are right on target.

**Comment by leewujung** [comment]
This issue is now resolved. In the 2024/01/29 meeting we also discussed this along with the bug in https://github.com/uw-echospace/EchoPro/issues/42.
