### ISSUE TITLE
Create basic user documentation

### ISSUE THREAD

**Issue by b-reyes** [uw-echospace/EchoPro#17]
Once we are satisfied with a working version of the API, we should create some very basic documentation. This documentation can include the basic API (using docstrings) and a simple Jupyter Notebook walking the user through a typical workflow. 

Note: This task should include an automatic generation of the documentation and the creation of a readthedocs.

**Comment by emiliom** [comment]
> This documentation can include the basic API (using docstrings) 

Already implemented in PR #90

> and a simple Jupyter Notebook walking the user through a typical workflow.

This was addressed earlier, prior to v0.3.0

**Comment by emiliom** [comment]
I'll close this issue and start a new one. The specific things called out in this issue (automatic API documentation and Jupyter notebooks) are completed.
