### ISSUE TITLE
Finalize user documentation

### ISSUE THREAD

**Issue by b-reyes** [uw-echospace/EchoPro#22]
Once we are happy with the state of EchoPro, a finalization of the user documentation should occur. This documentation should include an improvement of the basic documentation completed in #17. For example, we could include some more in depth Jupyter Notebook tutorials and document pages that describe how core routines have been implemented (e.g. biomass density calculation, Kriging, semi-variogram).

**Comment by leewujung** [comment]
I'll close this now since it's too high level. We'll add docs as we clean up the code and have confidence in the results.
