### ISSUE TITLE
Allow for user-defined functions in backscattering cross-section calculation

### ISSUE THREAD

**Issue by b-reyes** [uw-echospace/EchoPro#8]
In [_get_strata_sig_b](https://github.com/uw-echospace/EchoPro/blob/cb5c5393a51d82df5371fc5432fba70346b5eaeb/EchoPro/load_stratification_data/load_stratification_data.py#L120) we compute the backscattering cross-section. Within this calculation we hard code several calculations that are specific to Hake (see below). We should allow the user to provide their own functions for these calculations. This will improve the generality of this function. 

Code segments to generalize: 

https://github.com/uw-echospace/EchoPro/blob/cb5c5393a51d82df5371fc5432fba70346b5eaeb/EchoPro/load_stratification_data/load_stratification_data.py#L148-L152

https://github.com/uw-echospace/EchoPro/blob/cb5c5393a51d82df5371fc5432fba70346b5eaeb/EchoPro/load_stratification_data/load_stratification_data.py#L165-L169

https://github.com/uw-echospace/EchoPro/blob/cb5c5393a51d82df5371fc5432fba70346b5eaeb/EchoPro/load_stratification_data/load_stratification_data.py#L175-L176

**Comment by leewujung** [comment]
Duplicated in #115, so closing this.
