### ISSUE TITLE
Construction of NASC data files

### ISSUE THREAD

**Issue by b-reyes** [uw-echospace/EchoPro#83]
In the Matlab version of EchoPro there exist routines that allow one to construct the Excel files corresponding to the NASC data. In the current version of Python EchoPro we do not include these routines. The reason for their exclusion is that up to this point we have considered the NASC data as preliminary files (i.e. files that should be generated before using EchoPro). We need to decide if we would like to include the generation of the Excel files corresponding to the NASC data.

**Comment by leewujung** [comment]
I will close this issue because it is incorrect to treat the NASC file as something that FEAT will give us. The inputs to EchoPro are Echoview exports, and we need to be able to generate the NASC files.
