### ISSUE TITLE
Implement additional `source` options in `EchoPro.Survey`

### ISSUE THREAD

**Issue by b-reyes** [uw-echospace/EchoPro#93]
Currently only `source=3` has been implemented for `EchoPro.Survey` that uses both the US and Canada sections of the survey. However, the Matlab version does allow the user to run the entire workflow using either the US or Canada sections only. To allow for this, the Python version must make the following changes:
- Modify `biological_data.py` so that all files account for the other source options. This should be relatively straightforward. For example, if `source=1` (US only) then to correctly assign the length data one would do `self.survey.length_df = length_us_df`. 
- After quickly attempting to implement this, it was found that there are a couple of instances where index elements of DataFrames are selected when they do not exist. These errors are currently occurring when `survey_2019.compute_transect_results()` is ran. To correct this all instances where subsets of DataFrames are selected should be examined and one should ensure that the index exists in the DataFrame before using it. It is possible that correctly modifying the input `strata_df` to remove all unused stratum could resolve some of the initial errors produced.

**Comment by leewujung** [comment]
With the new changes in #161 and #164 this is pretty much addressed. I'll close this now since the description is outdated. If needed later we'll add another issue to track the source/country option.
